library(readr)
library(dplyr)
library(ggplot2)
salary_data <- read.csv("C:/Users/TUSHAR/Downloads/salary.csv")
print(salary_data)
salary <- na.omit(salary_data)
print(salary)
count_edu <- table(salary$EDU)
print(count_edu)
avg_edu <- mean(salary$EDU, na.rm = TRUE)
print(avg_edu)
median_edu <- median(salary$EDU, na.rm = TRUE)
print(median_edu)
highest_edu <- max(salary$EDU, na.rm = TRUE)
lowest_edu <- min(salary$EDU, na.rm = TRUE)
print(paste("Highest Education Level:", highest_edu))
print(paste("Lowest Education Level:", lowest_edu))
quartiles_edu <- quantile(salary$EDU)
print(quartiles_edu)
hist(salary$EDU, main = "Distribution of Education Levels", xlab = "Education Level (EDU)", ylab = "Frequency", col = "skyblue", border = "black")